# Generated by Django 6.0.2 on 2026-05-26 06:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_user_input', models.TextField(help_text='Original natural language request.')),
                ('structured_output', models.JSONField(blank=True, default=dict, help_text='Normalized AI pipeline output (versioned schema).')),
                ('urgency', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('emergency', 'Emergency')], db_index=True, default='medium', max_length=20)),
                ('location', models.JSONField(blank=True, default=dict, help_text='{"city","area","address","latitude","longitude"}')),
                ('locale', models.CharField(db_index=True, default='en', help_text='BCP-47 language code (en, mr).', max_length=10)),
                ('status', models.CharField(choices=[('pending_parse', 'Pending parse'), ('parsed', 'Parsed'), ('published', 'Published'), ('matching', 'Matching'), ('matched', 'Matched'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='pending_parse', max_length=20)),
                ('ai_confidence', models.DecimalField(blank=True, decimal_places=3, help_text='0.000–1.000 confidence from AI parser.', max_digits=4, null=True)),
                ('ai_provider', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_tasks', to=settings.AUTH_USER_MODEL)),
                ('detected_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='vendors.servicecategory')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['customer', 'status'], name='tasks_task_custome_f0edb6_idx'), models.Index(fields=['status', 'urgency'], name='tasks_task_status_e1758c_idx'), models.Index(fields=['locale', 'created_at'], name='tasks_task_locale_8fdb48_idx')],
            },
        ),
    ]
