# Generated by Django 6.0.2 on 2026-05-26 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine', models.CharField(choices=[('rule_based', 'Rule based'), ('ai', 'AI ranking')], default='rule_based', max_length=32)),
                ('engine_version', models.CharField(default='1.0', max_length=20)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], db_index=True, default='running', max_length=20)),
                ('candidate_count', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_runs', to='tasks.task')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveSmallIntegerField(db_index=True)),
                ('total_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('score_breakdown', models.JSONField(blank=True, default=dict, help_text='Per-factor scores for transparency and AI tuning.')),
                ('ai_score', models.DecimalField(blank=True, decimal_places=2, help_text='Reserved for future ML/AI re-ranking (0–100).', max_digits=5, null=True)),
                ('is_recommended', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_matches', to='tasks.task')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_matches', to='vendors.vendor')),
                ('match_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='matching.matchrun')),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
        migrations.AddIndex(
            model_name='matchrun',
            index=models.Index(fields=['task', 'created_at'], name='matching_ma_task_id_ec1ddb_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['task', 'rank'], name='matching_ma_task_id_36051a_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['task', '-total_score'], name='matching_ma_task_id_efa5a0_idx'),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.UniqueConstraint(fields=('match_run', 'vendor'), name='unique_vendor_per_match_run'),
        ),
    ]
