# Generated by Django 6.0.2 on 2026-05-26 06:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'service categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=200)),
                ('owner_name', models.CharField(max_length=150)),
                ('phone_number', models.CharField(db_index=True, max_length=15)),
                ('whatsapp_number', models.CharField(blank=True, default='', max_length=15)),
                ('subcategory', models.CharField(blank=True, default='', max_length=100)),
                ('city', models.CharField(db_index=True, default='Ichalkaranji', max_length=100)),
                ('area', models.CharField(db_index=True, help_text='Locality / area', max_length=120)),
                ('address', models.TextField()),
                ('description', models.TextField(blank=True, default='')),
                ('availability_status', models.CharField(choices=[('available', 'Available'), ('busy', 'Busy'), ('offline', 'Offline')], db_index=True, default='offline', max_length=20)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('profile_image', models.URLField(blank=True, default='', help_text='Placeholder URL until media upload is integrated.', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendors', to='vendors.servicecategory')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['city', 'area'], name='vendors_ven_city_f6e221_idx'), models.Index(fields=['category', 'verification_status'], name='vendors_ven_categor_5476e8_idx'), models.Index(fields=['availability_status', 'rating'], name='vendors_ven_availab_41a679_idx')],
            },
        ),
    ]
