# Generated by Django 6.0.2 on 2026-05-26 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pipeline', models.CharField(choices=[('task_intent_parser', 'Task intent parser')], max_length=64)),
                ('provider', models.CharField(choices=[('stub', 'Stub (rules)'), ('gemini', 'Google Gemini')], max_length=32)),
                ('locale', models.CharField(default='en', max_length=10)),
                ('raw_input', models.TextField()),
                ('structured_output', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], default='success', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('tokens_used', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
