# Generated by Django 6.0.2 on 2026-05-26 06:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_engine', '0001_initial'),
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='airequestlog',
            name='service_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_logs', to='tasks.task'),
        ),
        migrations.AddField(
            model_name='airequestlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_request_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='airequestlog',
            index=models.Index(fields=['pipeline', 'created_at'], name='ai_engine_a_pipelin_29f6e1_idx'),
        ),
        migrations.AddIndex(
            model_name='airequestlog',
            index=models.Index(fields=['user', 'created_at'], name='ai_engine_a_user_id_f48af9_idx'),
        ),
    ]
